[package]
name = "glass_pumpkin"
version = "1.9.0"
description = "A cryptographically secure prime number generator based on rust's own num-bigint and num-integer"
keywords = ["prime", "big", "cryptography", "generator", "number"]
license = "Apache-2.0"
authors = ["Michael Lodder <redmike7@gmail.com>"]
repository = "https://github.com/mikelodder7/glass_pumpkin"
documentation = "https://docs.rs/glass_pumpkin"
homepage = "https://crates.io/crates/glass_pumpkin"
readme = "README.md"
edition = "2024"
rust-version = "1.93"

[dependencies]
num-bigint = { version = "0.4", default-features = false, features = ["rand"] }
num-traits = { version = "0.2", default-features = false }
num-integer = { version = "0.1", default-features = false }
rand_core = { version = "0.10" }
getrandom = { version = "0.4", default-features = false, features = ["sys_rng"], optional = true }
once_cell = { version = "1.21", default-features = false, features = ["alloc"] }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
rand = "0.10"

[[bench]]
name = "gen_safe_prime"
harness = false

[profile.bench]
opt-level = 3

[features]
default = ["std", "getrandom"]
std = ["once_cell/std"]
# Enables methods that use `SysRng` internally
getrandom = ["dep:getrandom"]
# Enables compilation in `no_std` environment
no_std = ["once_cell/critical-section"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[patch.crates-io]
num-bigint = { git = "https://github.com/earthlings-dev/num-bigint.git" }
rand_core = { git = "https://github.com/earthlings-dev/rand_core.git" }
rand = { git = "https://github.com/earthlings-dev/rand.git" }
getrandom = { git = "https://github.com/earthlings-dev/getrandom.git" }
